        !COMPILER-GENERATED INTERFACE MODULE: Sun Jul 21 11:10:47 2013
        MODULE ALLOCATEWATERTOUSERS__genmod
          INTERFACE 
            SUBROUTINE ALLOCATEWATERTOUSERS(TIMESTEP,NUMNODE,NUMLINK,   &
     &NUMUSER,NUMRESERVOIR,NUMSOURCE,NUMRIGHTS,NUMSOURCEMIXING,         &
     &DRAINAGEORDER,NUMDRAINAGE,NUMRETURNFLOW,NUMUSERSOURCE,            &
     &VOLUME_IRRIG_SUP,GROUNDWATER_TO_TAKE,DRAINAGEOUTFLOW)
              INTEGER(KIND=4) :: NUMDRAINAGE
              INTEGER(KIND=4) :: TIMESTEP
              INTEGER(KIND=4) :: NUMNODE
              INTEGER(KIND=4) :: NUMLINK
              INTEGER(KIND=4) :: NUMUSER
              INTEGER(KIND=4) :: NUMRESERVOIR
              INTEGER(KIND=4) :: NUMSOURCE
              INTEGER(KIND=4) :: NUMRIGHTS
              INTEGER(KIND=4) :: NUMSOURCEMIXING
              INTEGER(KIND=4) :: DRAINAGEORDER(NUMDRAINAGE)
              INTEGER(KIND=4) :: NUMRETURNFLOW
              INTEGER(KIND=4) :: NUMUSERSOURCE
              REAL(KIND=8) :: VOLUME_IRRIG_SUP(*)
              REAL(KIND=8) :: GROUNDWATER_TO_TAKE(*)
              REAL(KIND=4) :: DRAINAGEOUTFLOW(NUMDRAINAGE)
            END SUBROUTINE ALLOCATEWATERTOUSERS
          END INTERFACE 
        END MODULE ALLOCATEWATERTOUSERS__genmod
