        !COMPILER-GENERATED INTERFACE MODULE: Sun Jul 21 11:10:45 2013
        MODULE BUILDNODESTRUCTURE__genmod
          INTERFACE 
            SUBROUTINE BUILDNODESTRUCTURE(NUMDRAINAGE,NUMUSER,          &
     &NUMRESERVOIR,NUMSOURCE,NUMRETURNFLOW,NUMMEASUREDFLOWINFO,NUMNODE)
              INTEGER(KIND=4) :: NUMDRAINAGE
              INTEGER(KIND=4) :: NUMUSER
              INTEGER(KIND=4) :: NUMRESERVOIR
              INTEGER(KIND=4) :: NUMSOURCE
              INTEGER(KIND=4) :: NUMRETURNFLOW
              INTEGER(KIND=4) :: NUMMEASUREDFLOWINFO
              INTEGER(KIND=4) :: NUMNODE
            END SUBROUTINE BUILDNODESTRUCTURE
          END INTERFACE 
        END MODULE BUILDNODESTRUCTURE__genmod
