        !COMPILER-GENERATED INTERFACE MODULE: Sun Jul 21 11:10:46 2013
        MODULE BUILDLINKSTRUCTURE__genmod
          INTERFACE 
            SUBROUTINE BUILDLINKSTRUCTURE(NUMDRAINAGE,NUMUSER,NUMSOURCE,&
     &NUMRETURNFLOW,NUMRESERVOIR,NUMMEASUREDFLOWINFO,NUMNODE,NUMLINK)
              INTEGER(KIND=4) :: NUMDRAINAGE
              INTEGER(KIND=4) :: NUMUSER
              INTEGER(KIND=4) :: NUMSOURCE
              INTEGER(KIND=4) :: NUMRETURNFLOW
              INTEGER(KIND=4) :: NUMRESERVOIR
              INTEGER(KIND=4) :: NUMMEASUREDFLOWINFO
              INTEGER(KIND=4) :: NUMNODE
              INTEGER(KIND=4) :: NUMLINK
            END SUBROUTINE BUILDLINKSTRUCTURE
          END INTERFACE 
        END MODULE BUILDLINKSTRUCTURE__genmod
