        !COMPILER-GENERATED INTERFACE MODULE: Sun Jul 21 11:10:47 2013
        MODULE BUILDDRAINAGEORDER__genmod
          INTERFACE 
            SUBROUTINE BUILDDRAINAGEORDER(NUMDRAINAGE,DRAINAGEORDER)
              INTEGER(KIND=4) :: NUMDRAINAGE
              INTEGER(KIND=4) :: DRAINAGEORDER(NUMDRAINAGE)
            END SUBROUTINE BUILDDRAINAGEORDER
          END INTERFACE 
        END MODULE BUILDDRAINAGEORDER__genmod
