        !COMPILER-GENERATED INTERFACE MODULE: Sun Jul 21 11:10:45 2013
        MODULE CREATENODE__genmod
          INTERFACE 
            SUBROUTINE CREATENODE(NUMNODE,TITLE,NODECODE,INTEXTCODE,    &
     &STOREMIN,STOREMAX,STORE,DRAINAGEID,SELFID)
              INTEGER(KIND=4) :: NUMNODE
              CHARACTER(LEN=6) :: TITLE
              INTEGER(KIND=4) :: NODECODE
              INTEGER(KIND=4) :: INTEXTCODE
              REAL(KIND=4) :: STOREMIN
              REAL(KIND=4) :: STOREMAX
              REAL(KIND=4) :: STORE
              INTEGER(KIND=4) :: DRAINAGEID
              INTEGER(KIND=4) :: SELFID
            END SUBROUTINE CREATENODE
          END INTERFACE 
        END MODULE CREATENODE__genmod
