        !COMPILER-GENERATED INTERFACE MODULE: Sun Jul 21 11:10:46 2013
        MODULE FIND3B__genmod
          INTERFACE 
            SUBROUTINE FIND3B(IARRAY1,IVAL1,IARRAY2,IVAL2,IARRAY3,IVAL3,&
     &NUM)
              INTEGER(KIND=4) :: NUM
              INTEGER(KIND=4) :: IARRAY1(NUM)
              INTEGER(KIND=4) :: IVAL1
              INTEGER(KIND=4) :: IARRAY2(NUM)
              INTEGER(KIND=4) :: IVAL2
              INTEGER(KIND=4) :: IARRAY3(NUM)
              INTEGER(KIND=4) :: IVAL3
            END SUBROUTINE FIND3B
          END INTERFACE 
        END MODULE FIND3B__genmod
