        !COMPILER-GENERATED INTERFACE MODULE: Sun Jul 21 11:10:47 2013
        MODULE INITIALISE_OUTPUT_TABLES__genmod
          INTERFACE 
            SUBROUTINE INITIALISE_OUTPUT_TABLES(NUMDRAINAGE,NUMNODE,    &
     &NUMSTREAMNODE,NUMLINK,NUMUSER,NUMTIMESTEPS,NUMRESERVOIR,          &
     &NUMUSERSOURCERETURN,NUMRETURNFLOW)
              INTEGER(KIND=4) :: NUMDRAINAGE
              INTEGER(KIND=4) :: NUMNODE
              INTEGER(KIND=4) :: NUMSTREAMNODE
              INTEGER(KIND=4) :: NUMLINK
              INTEGER(KIND=4) :: NUMUSER
              INTEGER(KIND=4) :: NUMTIMESTEPS
              INTEGER(KIND=4) :: NUMRESERVOIR
              INTEGER(KIND=4) :: NUMUSERSOURCERETURN
              INTEGER(KIND=4) :: NUMRETURNFLOW
            END SUBROUTINE INITIALISE_OUTPUT_TABLES
          END INTERFACE 
        END MODULE INITIALISE_OUTPUT_TABLES__genmod
