        !COMPILER-GENERATED INTERFACE MODULE: Sun Jul 21 11:10:43 2013
        MODULE ISRCH__genmod
          INTERFACE 
            FUNCTION ISRCH(MSITE,RSITE,NGAUGE)
              INTEGER(KIND=4) :: NGAUGE
              INTEGER(KIND=4) :: MSITE
              INTEGER(KIND=4) :: RSITE(NGAUGE)
              INTEGER(KIND=4) :: ISRCH
            END FUNCTION ISRCH
          END INTERFACE 
        END MODULE ISRCH__genmod
