        !COMPILER-GENERATED INTERFACE MODULE: Sun Jul 21 11:10:44 2013
        MODULE READ_LAKES_LEVELS__genmod
          INTERFACE 
            SUBROUTINE READ_LAKES_LEVELS(LAKE_REACH,LZERO,LAKE_AREAS,   &
     &LAKE_BEACH_SLPS,LK_LINE,NUM_RAT_VALS,LHEADS,LOFLOWS,INI_LEVELS,   &
     &MAX_LAKES,MAX_LHEADS)
              INTEGER(KIND=4) :: MAX_LHEADS
              INTEGER(KIND=4) :: MAX_LAKES
              INTEGER(KIND=4) :: LAKE_REACH(MAX_LAKES)
              INTEGER(KIND=4) :: LZERO(MAX_LAKES)
              REAL(KIND=4) :: LAKE_AREAS(MAX_LAKES)
              INTEGER(KIND=4) :: LAKE_BEACH_SLPS(MAX_LAKES)
              INTEGER(KIND=4) :: LK_LINE(MAX_LAKES)
              INTEGER(KIND=4) :: NUM_RAT_VALS(MAX_LAKES)
              INTEGER(KIND=4) :: LHEADS(MAX_LAKES,MAX_LHEADS)
              INTEGER(KIND=4) :: LOFLOWS(MAX_LAKES,MAX_LHEADS)
              REAL(KIND=4) :: INI_LEVELS(MAX_LAKES)
            END SUBROUTINE READ_LAKES_LEVELS
          END INTERFACE 
        END MODULE READ_LAKES_LEVELS__genmod
