        !COMPILER-GENERATED INTERFACE MODULE: Sun Jul 21 11:10:46 2013
        MODULE READ_INPUTS__genmod
          INTERFACE 
            SUBROUTINE READ_INPUTS(DIRNAME,DT,STARTDATETOPNET,          &
     &NUMDRAINAGE,NUMSTREAMNODE,NUMMEASUREDFLOWINFO,NUMMEASUREDFLOWDATA,&
     &NUMRESERVOIR,NUMUSER,NUMSOURCE,NUMRIGHTS,NUMSOURCEMIXING,         &
     &NUMSEASONSDEFN,NUMRETURNFLOW,NUMMONTHLYDEMAND,NUMRUNOFF,          &
     &NUMBASEFLOW,NUMWWTP)
              CHARACTER(LEN=128) :: DIRNAME
              INTEGER(KIND=4) :: DT
              INTEGER(KIND=4) :: STARTDATETOPNET
              INTEGER(KIND=4) :: NUMDRAINAGE
              INTEGER(KIND=4) :: NUMSTREAMNODE
              INTEGER(KIND=4) :: NUMMEASUREDFLOWINFO
              INTEGER(KIND=4) :: NUMMEASUREDFLOWDATA
              INTEGER(KIND=4) :: NUMRESERVOIR
              INTEGER(KIND=4) :: NUMUSER
              INTEGER(KIND=4) :: NUMSOURCE
              INTEGER(KIND=4) :: NUMRIGHTS
              INTEGER(KIND=4) :: NUMSOURCEMIXING
              INTEGER(KIND=4) :: NUMSEASONSDEFN
              INTEGER(KIND=4) :: NUMRETURNFLOW
              INTEGER(KIND=4) :: NUMMONTHLYDEMAND
              INTEGER(KIND=4) :: NUMRUNOFF
              INTEGER(KIND=4) :: NUMBASEFLOW
              INTEGER(KIND=4) :: NUMWWTP
            END SUBROUTINE READ_INPUTS
          END INTERFACE 
        END MODULE READ_INPUTS__genmod
