        !COMPILER-GENERATED INTERFACE MODULE: Sun Jul 21 11:10:47 2013
        MODULE REMOVE_ELEMENT__genmod
          INTERFACE 
            SUBROUTINE REMOVE_ELEMENT(J_OUT,NJ_OUT,IFOUND)
              INTEGER(KIND=4) :: NJ_OUT
              INTEGER(KIND=4) :: J_OUT(NJ_OUT)
              INTEGER(KIND=4) :: IFOUND
            END SUBROUTINE REMOVE_ELEMENT
          END INTERFACE 
        END MODULE REMOVE_ELEMENT__genmod
