        !COMPILER-GENERATED INTERFACE MODULE: Sun Jul 21 11:10:44 2013
        MODULE TD8MICSEC__genmod
          INTERFACE 
            SUBROUTINE TD8MICSEC(JDATEM,JHOUR,ISEC)
              INTEGER(KIND=4) :: JDATEM
              INTEGER(KIND=4) :: JHOUR
              INTEGER(KIND=8) :: ISEC
            END SUBROUTINE TD8MICSEC
          END INTERFACE 
        END MODULE TD8MICSEC__genmod
