        !COMPILER-GENERATED INTERFACE MODULE: Sun Jul 21 11:10:47 2013
        MODULE TRIALFLOW__genmod
          INTERFACE 
            SUBROUTINE TRIALFLOW(DEMANDBYUSERONSOURCE,I,J,J_SOURCE,     &
     &NUMNODE,NUMLINK,NUMUSER,NUMSOURCE,NUMRIGHTS,QTRY)
              REAL(KIND=4) :: DEMANDBYUSERONSOURCE
              INTEGER(KIND=4) :: I
              INTEGER(KIND=4) :: J
              INTEGER(KIND=4) :: J_SOURCE
              INTEGER(KIND=4) :: NUMNODE
              INTEGER(KIND=4) :: NUMLINK
              INTEGER(KIND=4) :: NUMUSER
              INTEGER(KIND=4) :: NUMSOURCE
              INTEGER(KIND=4) :: NUMRIGHTS
              REAL(KIND=4) :: QTRY
            END SUBROUTINE TRIALFLOW
          END INTERFACE 
        END MODULE TRIALFLOW__genmod
