        !COMPILER-GENERATED INTERFACE MODULE: Sun Jul 21 11:10:44 2013
        MODULE UPDATETIME__genmod
          INTERFACE 
            SUBROUTINE UPDATETIME(YEAR,MONTH,DAY,HOUR,DT)
              INTEGER(KIND=4) :: YEAR
              INTEGER(KIND=4) :: MONTH
              INTEGER(KIND=4) :: DAY
              REAL(KIND=4) :: HOUR
              REAL(KIND=4) :: DT
            END SUBROUTINE UPDATETIME
          END INTERFACE 
        END MODULE UPDATETIME__genmod
