        !COMPILER-GENERATED INTERFACE MODULE: Sun Jul 21 11:10:46 2013
        MODULE WRITE_STATIC_OUTPUT_TABLES__genmod
          INTERFACE 
            SUBROUTINE WRITE_STATIC_OUTPUT_TABLES(DIRNAME)
              CHARACTER(LEN=128) :: DIRNAME
            END SUBROUTINE WRITE_STATIC_OUTPUT_TABLES
          END INTERFACE 
        END MODULE WRITE_STATIC_OUTPUT_TABLES__genmod
