        !COMPILER-GENERATED INTERFACE MODULE: Sun Jul 21 11:10:47 2013
        MODULE WRITE_OUTPUTLINE__genmod
          INTERFACE 
            SUBROUTINE WRITE_OUTPUTLINE(FILENM,TIMESTEP,RVARIABLE,      &
     &NUMDRAINAGE,ICALL,SCALEFACTOR)
              INTEGER(KIND=4) :: NUMDRAINAGE
              CHARACTER(*) :: FILENM
              INTEGER(KIND=4) :: TIMESTEP
              REAL(KIND=8) :: RVARIABLE(NUMDRAINAGE)
              INTEGER(KIND=4) :: ICALL
              REAL(KIND=8) :: SCALEFACTOR
            END SUBROUTINE WRITE_OUTPUTLINE
          END INTERFACE 
        END MODULE WRITE_OUTPUTLINE__genmod
