        !COMPILER-GENERATED INTERFACE MODULE: Wed Jun 26 16:19:26 2013
        MODULE APPEND_TO_OUTPUT_TABLES__genmod
          INTERFACE 
            SUBROUTINE APPEND_TO_OUTPUT_TABLES(TIMESTEP,DT,             &
     &DRAINAGEOUTFLOW,NUMDRAINAGE,NUMSTREAMNODE,YYYYMMDD,HHMMSS,        &
     &PRECIPITATION,EVAPORATION,NUMLINK,NUMNODE,NSTEPS,NUMUSER)
              INTEGER(KIND=4) :: NUMDRAINAGE
              INTEGER(KIND=4) :: TIMESTEP
              INTEGER(KIND=4) :: DT
              REAL(KIND=4) :: DRAINAGEOUTFLOW(NUMDRAINAGE)
              INTEGER(KIND=4) :: NUMSTREAMNODE
              INTEGER(KIND=4) :: YYYYMMDD
              INTEGER(KIND=4) :: HHMMSS
              REAL(KIND=8) :: PRECIPITATION(*)
              REAL(KIND=8) :: EVAPORATION(*)
              INTEGER(KIND=4) :: NUMLINK
              INTEGER(KIND=4) :: NUMNODE
              INTEGER(KIND=4) :: NSTEPS
              INTEGER(KIND=4) :: NUMUSER
            END SUBROUTINE APPEND_TO_OUTPUT_TABLES
          END INTERFACE 
        END MODULE APPEND_TO_OUTPUT_TABLES__genmod
