        !COMPILER-GENERATED INTERFACE MODULE: Wed Jun 26 16:19:24 2013
        MODULE ASSIGNPRIORITYORDER__genmod
          INTERFACE 
            SUBROUTINE ASSIGNPRIORITYORDER(NUMUSER,NUMSOURCE,NUMRIGHTS, &
     &NUMRESERVOIR,ALLOCATIONMODE,DRAINAGEORDER,NUMDRAINAGE,            &
     &NUMUSERSOURCE,NUMUSERSOURCERETURN,NUMRETURNFLOW)
              INTEGER(KIND=4) :: NUMUSER
              INTEGER(KIND=4) :: NUMSOURCE
              INTEGER(KIND=4) :: NUMRIGHTS
              INTEGER(KIND=4) :: NUMRESERVOIR
              INTEGER(KIND=4) :: ALLOCATIONMODE
              INTEGER(KIND=4) :: DRAINAGEORDER(*)
              INTEGER(KIND=4) :: NUMDRAINAGE
              INTEGER(KIND=4) :: NUMUSERSOURCE
              INTEGER(KIND=4) :: NUMUSERSOURCERETURN
              INTEGER(KIND=4) :: NUMRETURNFLOW
            END SUBROUTINE ASSIGNPRIORITYORDER
          END INTERFACE 
        END MODULE ASSIGNPRIORITYORDER__genmod
