        !COMPILER-GENERATED INTERFACE MODULE: Wed Jun 26 16:19:23 2013
        MODULE BUILDDRAINAGEORDER__genmod
          INTERFACE 
            SUBROUTINE BUILDDRAINAGEORDER(NUMDRAINAGE,DRAINAGEORDER)
              INTEGER(KIND=4) :: NUMDRAINAGE
              INTEGER(KIND=4) :: DRAINAGEORDER(NUMDRAINAGE)
            END SUBROUTINE BUILDDRAINAGEORDER
          END INTERFACE 
        END MODULE BUILDDRAINAGEORDER__genmod
