        !COMPILER-GENERATED INTERFACE MODULE: Wed Jun 26 16:19:24 2013
        MODULE CALCULATEDEMAND__genmod
          INTERFACE 
            SUBROUTINE CALCULATEDEMAND(THISMONTH,DOY,VOL_IRRIG_DEMAND,  &
     &NUMUSER,NUMMONTHLYDEMAND)
              INTEGER(KIND=4) :: THISMONTH
              INTEGER(KIND=4) :: DOY
              REAL(KIND=8) :: VOL_IRRIG_DEMAND(*)
              INTEGER(KIND=4) :: NUMUSER
              INTEGER(KIND=4) :: NUMMONTHLYDEMAND
            END SUBROUTINE CALCULATEDEMAND
          END INTERFACE 
        END MODULE CALCULATEDEMAND__genmod
