        !COMPILER-GENERATED INTERFACE MODULE: Wed Jun 26 16:19:25 2013
        MODULE CREATESOURCE__genmod
          INTERFACE 
            SUBROUTINE CREATESOURCE(NUMSOURCE,SOURCESTYPE,              &
     &SOURCELOCATIONID,REALSOURCELOCATIONID,PHYSICALDAILYMAX,           &
     &PHYSICALANNMAX)
              INTEGER(KIND=4) :: NUMSOURCE
              INTEGER(KIND=4) :: SOURCESTYPE
              INTEGER(KIND=4) :: SOURCELOCATIONID
              INTEGER(KIND=4) :: REALSOURCELOCATIONID
              REAL(KIND=4) :: PHYSICALDAILYMAX
              REAL(KIND=4) :: PHYSICALANNMAX
            END SUBROUTINE CREATESOURCE
          END INTERFACE 
        END MODULE CREATESOURCE__genmod
