        !COMPILER-GENERATED INTERFACE MODULE: Wed Jun 26 16:19:25 2013
        MODULE CREATERETURNFLOW__genmod
          INTERFACE 
            SUBROUTINE CREATERETURNFLOW(NUMRETURNFLOW,NUMRETURNFLOWS,   &
     &RETURNFLOWSUNITS,RETURNFLOWSAMT,RETURNFLOWSTYPE,RETURNFLOWSLOCN)
              INTEGER(KIND=4) :: NUMRETURNFLOW
              INTEGER(KIND=4) :: NUMRETURNFLOWS
              INTEGER(KIND=4) :: RETURNFLOWSUNITS
              REAL(KIND=4) :: RETURNFLOWSAMT
              INTEGER(KIND=4) :: RETURNFLOWSTYPE
              INTEGER(KIND=4) :: RETURNFLOWSLOCN
            END SUBROUTINE CREATERETURNFLOW
          END INTERFACE 
        END MODULE CREATERETURNFLOW__genmod
