        !COMPILER-GENERATED INTERFACE MODULE: Wed Jun 26 16:19:25 2013
        MODULE CREATEUSER__genmod
          INTERFACE 
            SUBROUTINE CREATEUSER(NUMUSER,USERSTYPE,POU_ID,DEMANDTYPE,  &
     &DEMANDVBLE,DEMANDRATE,INYEARDEMANDTYPE,RETURNFLOWID,SOURCEMIXINGID&
     &,NUMSOURCES,SOURCEID,RIGHTID)
              INTEGER(KIND=4) :: NUMUSER
              INTEGER(KIND=4) :: USERSTYPE
              INTEGER(KIND=4) :: POU_ID
              INTEGER(KIND=4) :: DEMANDTYPE
              REAL(KIND=4) :: DEMANDVBLE
              REAL(KIND=4) :: DEMANDRATE
              INTEGER(KIND=4) :: INYEARDEMANDTYPE
              INTEGER(KIND=4) :: RETURNFLOWID
              INTEGER(KIND=4) :: SOURCEMIXINGID
              INTEGER(KIND=4) :: NUMSOURCES
              INTEGER(KIND=4) :: SOURCEID
              INTEGER(KIND=4) :: RIGHTID
            END SUBROUTINE CREATEUSER
          END INTERFACE 
        END MODULE CREATEUSER__genmod
