        !COMPILER-GENERATED INTERFACE MODULE: Wed Jun 26 16:19:24 2013
        MODULE IMPOSEMEASUREDFLOWS__genmod
          INTERFACE 
            SUBROUTINE IMPOSEMEASUREDFLOWS(TIMESTEP,NUMNODE,NUMLINK,    &
     &NUMRUNOFF,NUMBASEFLOW,NUMDRAINAGE,NUMMEASUREDFLOWINFO,            &
     &NUMMEASUREDFLOWDATA,DRAINAGEORDER,DRAINAGEOUTFLOW)
              INTEGER(KIND=4) :: NUMDRAINAGE
              INTEGER(KIND=4) :: TIMESTEP
              INTEGER(KIND=4) :: NUMNODE
              INTEGER(KIND=4) :: NUMLINK
              INTEGER(KIND=4) :: NUMRUNOFF
              INTEGER(KIND=4) :: NUMBASEFLOW
              INTEGER(KIND=4) :: NUMMEASUREDFLOWINFO
              INTEGER(KIND=4) :: NUMMEASUREDFLOWDATA
              INTEGER(KIND=4) :: DRAINAGEORDER(NUMDRAINAGE)
              REAL(KIND=4) :: DRAINAGEOUTFLOW(NUMDRAINAGE)
            END SUBROUTINE IMPOSEMEASUREDFLOWS
          END INTERFACE 
        END MODULE IMPOSEMEASUREDFLOWS__genmod
