        !COMPILER-GENERATED INTERFACE MODULE: Wed Jun 26 16:19:22 2013
        MODULE IRRIGATION__genmod
          INTERFACE 
            SUBROUTINE IRRIGATION(SR,SP,JS,INTERV,MAXSLP,DAPP)
              INTEGER(KIND=4) :: MAXSLP
              REAL(KIND=8) :: SR
              REAL(KIND=8) :: SP(39,MAXSLP)
              INTEGER(KIND=4) :: JS
              INTEGER(KIND=8) :: INTERV
              REAL(KIND=8) :: DAPP
            END SUBROUTINE IRRIGATION
          END INTERFACE 
        END MODULE IRRIGATION__genmod
