        !COMPILER-GENERATED INTERFACE MODULE: Wed Jun 26 16:19:22 2013
        MODULE RAINFILL_READ__genmod
          INTERFACE 
            SUBROUTINE RAINFILL_READ(RAINFILL_FILE,NGAUGE,RSITE,RCOEFF, &
     &FSITE,NFILL,FILLFLAG,MAXGAUGE)
              INTEGER(KIND=4) :: MAXGAUGE
              CHARACTER(LEN=128) :: RAINFILL_FILE
              INTEGER(KIND=4) :: NGAUGE
              INTEGER(KIND=4) :: RSITE(MAXGAUGE)
              REAL(KIND=4) :: RCOEFF(MAXGAUGE,MAXGAUGE)
              INTEGER(KIND=4) :: FSITE(MAXGAUGE,MAXGAUGE)
              INTEGER(KIND=4) :: NFILL(MAXGAUGE)
              INTEGER(KIND=4) :: FILLFLAG
            END SUBROUTINE RAINFILL_READ
          END INTERFACE 
        END MODULE RAINFILL_READ__genmod
