        !COMPILER-GENERATED INTERFACE MODULE: Wed Jun 26 16:19:25 2013
        MODULE READ_STRUCT_FROM_TEXT__genmod
          INTERFACE 
            SUBROUTINE READ_STRUCT_FROM_TEXT(FILENM,EXPECTED_NUMCOLS,   &
     &NCOMMENTLINES,NROWS)
              CHARACTER(*) :: FILENM
              INTEGER(KIND=4) :: EXPECTED_NUMCOLS
              INTEGER(KIND=4) :: NCOMMENTLINES
              INTEGER(KIND=4) :: NROWS
            END SUBROUTINE READ_STRUCT_FROM_TEXT
          END INTERFACE 
        END MODULE READ_STRUCT_FROM_TEXT__genmod
