        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 02 09:35:32 2013
        MODULE READ_LAKES__genmod
          INTERFACE 
            SUBROUTINE READ_LAKES(LAKE_REACH,LZERO,LAKE_AREAS,          &
     &LAKE_BEACH_SLPS,LK_LINE,NUM_RAT_VALS,LHEADS,LOFLOWS,MAX_LAKES,    &
     &MAX_LHEADS)
              INTEGER(KIND=4) :: MAX_LHEADS
              INTEGER(KIND=4) :: MAX_LAKES
              INTEGER(KIND=4) :: LAKE_REACH(MAX_LAKES)
              INTEGER(KIND=4) :: LZERO(MAX_LAKES)
              REAL(KIND=4) :: LAKE_AREAS(MAX_LAKES)
              INTEGER(KIND=4) :: LAKE_BEACH_SLPS(MAX_LAKES)
              INTEGER(KIND=4) :: LK_LINE(MAX_LAKES)
              INTEGER(KIND=4) :: NUM_RAT_VALS(MAX_LAKES)
              INTEGER(KIND=4) :: LHEADS(MAX_LAKES,MAX_LHEADS)
              INTEGER(KIND=4) :: LOFLOWS(MAX_LAKES,MAX_LHEADS)
            END SUBROUTINE READ_LAKES
          END INTERFACE 
        END MODULE READ_LAKES__genmod
