        !COMPILER-GENERATED INTERFACE MODULE: Wed Jun 26 16:19:24 2013
        MODULE SCALEUPSTREAMRUNOFF__genmod
          INTERFACE 
            SUBROUTINE SCALEUPSTREAMRUNOFF(FLOWRATIO,K,TIMESTEP,NUMNODE,&
     &NUMRUNOFF,NUMBASEFLOW,NUMDRAINAGE)
              REAL(KIND=4) :: FLOWRATIO
              INTEGER(KIND=4) :: K
              INTEGER(KIND=4) :: TIMESTEP
              INTEGER(KIND=4) :: NUMNODE
              INTEGER(KIND=4) :: NUMRUNOFF
              INTEGER(KIND=4) :: NUMBASEFLOW
              INTEGER(KIND=4) :: NUMDRAINAGE
            END SUBROUTINE SCALEUPSTREAMRUNOFF
          END INTERFACE 
        END MODULE SCALEUPSTREAMRUNOFF__genmod
