        !COMPILER-GENERATED INTERFACE MODULE: Wed Jun 26 16:19:23 2013
        MODULE SETORDER__genmod
          INTERFACE 
            RECURSIVE SUBROUTINE SETORDER(K,DRAINAGEORDER,POSITION,     &
     &NUMDRAINAGE)
              INTEGER(KIND=4) :: NUMDRAINAGE
              INTEGER(KIND=4) :: K
              INTEGER(KIND=4) :: DRAINAGEORDER(NUMDRAINAGE)
              INTEGER(KIND=4) :: POSITION
            END SUBROUTINE SETORDER
          END INTERFACE 
        END MODULE SETORDER__genmod
