        !COMPILER-GENERATED INTERFACE MODULE: Wed Jun 26 16:19:21 2013
        MODULE SNOWUEB__genmod
          INTERFACE 
            SUBROUTINE SNOWUEB(SNOWSITEV,SNOWSTATEV,SNOWPARAM,          &
     &NDEPLETIONPOINTS,DFC,SNOWCONTROL,DTBAR,SNOWFORCING,SNOWSURFACETEMP&
     &,SNOWAVERAGETEMP,TIMESTEP,NSTEPDAY,SURFACEWATERINPUT,             &
     &SNOWEVAPORATION,AREAFRACTIONSNOW,MODELELEMENT)
              INTEGER(KIND=4) :: NDEPLETIONPOINTS
              REAL(KIND=4) :: SNOWSITEV(1)
              REAL(KIND=4) :: SNOWSTATEV(1)
              REAL(KIND=4) :: SNOWPARAM(1)
              REAL(KIND=4) :: DFC(NDEPLETIONPOINTS,2)
              INTEGER(KIND=4) :: SNOWCONTROL(1)
              REAL(KIND=4) :: DTBAR(12)
              REAL(KIND=4) :: SNOWFORCING(1)
              REAL(KIND=4) :: SNOWSURFACETEMP(*)
              REAL(KIND=4) :: SNOWAVERAGETEMP(*)
              REAL(KIND=4) :: TIMESTEP
              INTEGER(KIND=4) :: NSTEPDAY
              REAL(KIND=4) :: SURFACEWATERINPUT
              REAL(KIND=4) :: SNOWEVAPORATION
              REAL(KIND=4) :: AREAFRACTIONSNOW
              INTEGER(KIND=4) :: MODELELEMENT
            END SUBROUTINE SNOWUEB
          END INTERFACE 
        END MODULE SNOWUEB__genmod
