        !COMPILER-GENERATED INTERFACE MODULE: Wed Jun 26 16:19:23 2013
        MODULE TD81MICDH__genmod
          INTERFACE 
            SUBROUTINE TD81MICDH(IDATE,IHOUR,JSEC)
              INTEGER(KIND=4) :: IDATE
              INTEGER(KIND=4) :: IHOUR
              INTEGER(KIND=8) :: JSEC
            END SUBROUTINE TD81MICDH
          END INTERFACE 
        END MODULE TD81MICDH__genmod
