        !COMPILER-GENERATED INTERFACE MODULE: Wed Jun 26 16:19:23 2013
        MODULE WRITE_STRUCT_TO_TEXT__genmod
          INTERFACE 
            SUBROUTINE WRITE_STRUCT_TO_TEXT(FILENM,HEADERS,NROWS,NCOLS, &
     &ICALL)
              CHARACTER(LEN=128) :: FILENM
              CHARACTER(LEN=12) :: HEADERS(*)
              INTEGER(KIND=4) :: NROWS
              INTEGER(KIND=4) :: NCOLS
              INTEGER(KIND=4) :: ICALL
            END SUBROUTINE WRITE_STRUCT_TO_TEXT
          END INTERFACE 
        END MODULE WRITE_STRUCT_TO_TEXT__genmod
