        !COMPILER-GENERATED INTERFACE MODULE: Wed Jun 26 16:19:23 2013
        MODULE WRITE_INTEGERS_TO_TEXT__genmod
          INTERFACE 
            SUBROUTINE WRITE_INTEGERS_TO_TEXT(FILENM,HEADERS,NROWS,NCOLS&
     &)
              CHARACTER(LEN=128) :: FILENM
              CHARACTER(LEN=30) :: HEADERS(*)
              INTEGER(KIND=4) :: NROWS
              INTEGER(KIND=4) :: NCOLS
            END SUBROUTINE WRITE_INTEGERS_TO_TEXT
          END INTERFACE 
        END MODULE WRITE_INTEGERS_TO_TEXT__genmod
