        !COMPILER-GENERATED INTERFACE MODULE: Wed Jun 26 16:19:23 2013
        MODULE WRITE_TIMEVARYINGOUTPUT_TABLES__genmod
          INTERFACE 
            SUBROUTINE WRITE_TIMEVARYINGOUTPUT_TABLES(DIRNAME,NUMUSER,  &
     &NUMTIMESTEPS,NUMNODE,NUMLINK,NUMRETURNFLOW,NUMWWTP)
              CHARACTER(LEN=128) :: DIRNAME
              INTEGER(KIND=4) :: NUMUSER
              INTEGER(KIND=4) :: NUMTIMESTEPS
              INTEGER(KIND=4) :: NUMNODE
              INTEGER(KIND=4) :: NUMLINK
              INTEGER(KIND=4) :: NUMRETURNFLOW
              INTEGER(KIND=4) :: NUMWWTP
            END SUBROUTINE WRITE_TIMEVARYINGOUTPUT_TABLES
          END INTERFACE 
        END MODULE WRITE_TIMEVARYINGOUTPUT_TABLES__genmod
